CREATE TABLE Categorys (
    CategoryID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL
);
CREATE TABLE Brands (
    BrandID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    BrandName VARCHAR(100) NOT NULL
);
CREATE TABLE Products (
    ProductID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    category_id BIGINT UNSIGNED,
    brand_id BIGINT UNSIGNED,
    Description VARCHAR(255),
    Price DECIMAL(10,2) NOT NULL,
    StockQty INT NOT NULL DEFAULT 0,
    img VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_category FOREIGN KEY (category_id) 
        REFERENCES Categorys(CategoryID) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE,

    CONSTRAINT fk_brand FOREIGN KEY (brand_id) 
        REFERENCES Brands(BrandID) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

CREATE TABLE newProducts (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL, 
    `des` VARCHAR(255),
    `price` DECIMAL(10,2) NOT NULL,
    `img` VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



